[package]

name = "irsc"
version = "0.0.3"
authors = ["Till Hoeppner <till@hoeppner.ws>"]
description = "A lightweight library for building IRC bots."
repository = "https://github.com/tilpner/irsc"
keywords = ["irc", "internet", "protocol"]
license = "MIT"

[dependencies]
log = "*"
env_logger = "*"
regex = "*"
regex_macros = "*"

[features]
ssl = ["openssl"]

[dependencies.openssl]
version = "*"
optional = true
